### ISSUE TITLE
Bug: clearing failed notches

### ISSUE THREAD

**Issue by IYOV-git** [patrickburk1988/unknownarmies#1]
Hey,

thanks for your excellent work, but I think I noticed a little bug. When I remove failed notches by clicking on FAILED, they are visible again as soon as I change something else on the sheet.

Maybe I'm missing something, but a way to shift rolls (+/- X) would also be great.

Again thank you!

**Comment by patrickburk1988** [comment]
Thanks for the report! I've also noticed changes to failed notches not always saving. Currently investigating this, but I'm kind of flummoxed. I think it may have something to do with the way Foundry itself updates the sheet data when a radio button is clicked?

I'll keep looking into the issue, but in the meantime: I've noticed that if you change the failed notches, then click a "blank" spot on the sheet (like somewhere in the margins), then close the sheet and reopen it before making any further edits, that the changes you've made to the failed notches are more liable to stick. And though it's by no means an ideal solution, you can also export the sheet to a JSON file, manually edit the failed value in question, and then re-import the file.

Until I get it fixed, sorry for the bug! And as for a way to shift rolls, I'm hoping to implement this feature soon!

**Comment by patrickburk1988** [comment]
This should be fixed in the latest release (fingers crossed). Let me know if issue reoccurs.

**Comment by IYOV-git** [comment]
Hey, I tested the last update and it works perfectly. Thank you!
